### ISSUE TITLE
Unable to install maven-plugin from Maven Central

### ISSUE THREAD

**Issue by hhiptmair** [BerkleyTechnologyServices/restdocs-spec#142]
Hi!
I'm having issues using the restdocs-spec-maven-plugin in its latest version 0.21 when trying to download it from Maven Central. 
The same issue is reproducible when trying to build the example from https://github.com/BerkleyTechnologyServices/restdocs-spec-example and the warnings/errors are the ones below:

> [INFO]
[INFO] -----< io.github.berkleytechnologyservices:restdocs-spec-example >------
[INFO] Building restdocs-spec-example 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-maven-plugin/2.5.2/spring-boot-maven-plugin-2.5.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-maven-plugin/2.5.2/spring-boot-maven-plugin-2.5.2.pom (3.1 kB at 67 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-maven-plugin/2.5.2/spring-boot-maven-plugin-2.5.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-maven-plugin/2.5.2/spring-boot-maven-plugin-2.5.2.jar (102 kB at 2.0 MB/s)
[WARNING] The POM for io.github.berkleytechnologyservices:restdocs-spec-maven-plugin:jar:0.21 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.841 s
[INFO] Finished at: 2021-06-29T10:03:32+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin io.github.berkleytechnologyservices:restdocs-spec-maven-plugin:0.21 or one of its dependencies could not be resolved: Failed to read artifact descriptor for io.github.berkleytechnologyservices:restdocs-spec-maven-plugin:jar:0.21: 6 problems were encountered while building the effective model for io.github.berkleytechnologyservices:restdocs-spec-maven-plugin:0.21
[ERROR] [ERROR] Invalid packaging for parent POM io.github.berkleytechnologyservices:restdocs-spec:0.21, must be "pom" but is "jar" @ io.github.berkleytechnologyservices:restdocs-spec:0.21
[ERROR] [ERROR] 'dependencies.dependency.version' for org.apache.maven:maven-plugin-api:jar is missing. @
[ERROR] [ERROR] 'dependencies.dependency.version' for org.apache.maven:maven-core:jar is missing. @
[ERROR] [ERROR] 'dependencies.dependency.version' for org.apache.maven:maven-artifact:jar is missing. @
[ERROR] [ERROR] 'dependencies.dependency.version' for org.apache.maven.plugin-tools:maven-plugin-annotations:jar is missing. @
[ERROR] [ERROR] 'dependencies.dependency.version' for com.epages:restdocs-api-spec-model:jar is missing. @
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

I'm not 100% sure whether this is an issue with the pom.xml released to Maven Central or the pom.xml of the example project. Any pointers welcome, thanks!

**Comment by klieber** [comment]
@hhiptmair Not sure why you are hitting that.  The example project has been building just fine:

https://github.com/BerkleyTechnologyServices/restdocs-spec-example/actions?query=branch%3Amaster

I also pull it down and it builds great on my local machine.  

Further, the errors don't really line up with reality:

Parent POM definitely has the type of `pom` not `jar`.
https://repo1.maven.org/maven2/io/github/berkleytechnologyservices/restdocs-spec/0.21/restdocs-spec-0.21.pom

Maybe try clearing your local `~/.m2/repository` directory.  Possibly something got corrupted there.

**Comment by hhiptmair** [comment]
Thanks @klieber! Clearing the local maven repository cache helped. Maybe this issue appeared as I was using the previously published maven plugin from JCenter already? 
Thanks again, you can close this issue :)
