### ISSUE TITLE
Add support for OpenAPI 3.0

### ISSUE THREAD

**Issue by klieber** [BerkleyTechnologyServices/restdocs-spec#16]

**Comment by cnsgithub** [comment]
@klieber Would really like to see support for OpenAPI 3.0. Are you still planning to support it?

**Comment by cnsgithub** [comment]
PR: #21

**Comment by bjornharvold** [comment]
Since postman already supports support for OpenAPI 3, this is a great extra feature.

**Comment by cnsgithub** [comment]
If you want to try it out, you can look at https://github.com/cnsgithub/restdocs-spec/tree/0.10-cns or the according jitpack release https://jitpack.io/#cnsgithub/restdocs-spec/0.10.4-cns, until it is merged here.

**Comment by bjornharvold** [comment]
Thank you :-) Will have a look.
