### ISSUE TITLE
Deploy the plugin to Maven Central

### ISSUE THREAD

**Issue by klieber** [BerkleyTechnologyServices/restdocs-spec#19]

**Comment by bjornharvold** [comment]
YES PLEASE

**Comment by ChrisDeBruyne** [comment]
@klieber anything we can help with?

**Comment by klieber** [comment]
First step is getting restdocs-api-spec in maven central.  I just opened a pull request to that project to remove their final dependency on Jitpack.  If they merge that and push their project to maven central then I should be able to do that same with restdocs-spec-maven-plugin.

**Comment by klieber** [comment]
Going to need to bump the priority on this now that JCenter is being shutdown:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by klieber** [comment]
Should be in maven central with version [0.20](https://github.com/BerkleyTechnologyServices/restdocs-spec/releases/tag/0.20).
