### ISSUE TITLE
Readme does not show support for OpenAPI V3

### ISSUE THREAD

**Issue by smver** [BerkleyTechnologyServices/restdocs-spec#25]
Per [https://github.com/BerkleyTechnologyServices/restdocs-spec/pull/21](https://github.com/BerkleyTechnologyServices/restdocs-spec/pull/21), support for OpenAPI V3 has been added, but the readme does not show this. I made the necessary changes locally but do not have permission to push the new branch up and therefore cannot open a PR.

**Comment by kylehoehns** [comment]
@smver Thanks for the heads up! I think you'd be able to fork this project and open a pull request from your fork to this one. Examples of others doing that would be in #21 and #22.

**Comment by klieber** [comment]
This has been resolved with #26
