### ISSUE TITLE
Do not fail on unknown properties

### ISSUE THREAD

**Issue by mduesterhoeft** [BerkleyTechnologyServices/restdocs-spec#30]
I have an issue in restdocs-api-spec where users complain about unknown fields in the `ResourceSnippet` cause errors - see https://github.com/ePages-de/restdocs-api-spec/issues/82

Looking at the code I found that the `ObjectMapper` instance you use does not ignore unknown properties.

https://github.com/BerkleyTechnologyServices/restdocs-spec/blob/eb2950ce45f381d2599ba5c27bdbfdb5d156e8e9/restdocs-spec-maven-plugin/src/main/java/com/berkleytechnologyservices/restdocs/mojo/SnippetReader.java#L25

**Comment by klieber** [comment]
This should be fixed now in version 0.12
