### ISSUE TITLE
Unknown properties in ResourceModel fail the build

### ISSUE THREAD

**Issue by SanderSmee** [BerkleyTechnologyServices/restdocs-spec#32]
The fix for #30 doesn't result in the expected behaviour. 
On line 27 of `com.berkleytechnologyservices.restdocs.mojo.SnippetReader` the feature _fail on unknown properties_ should be disabled.

According to the documentation of Jackson `DeseriazationFeature.FAIL_ON_IGNORED_PROPERTIES` relates to excplicitly `@JsonIgnore`d attributes in a model.
For the (correct) fix of #30 I'd expect `DeseriazationFeature.FAIL_ON_UNKNOWN_PROPERTIES` which ignores attributes which aren't defined on a model.

**Comment by klieber** [comment]
Good catch.  I will get that fixed.

**Comment by SanderSmee** [comment]
I confirm the fix now works as expected.
Thanks.
